### ISSUE TITLE
Fix characters naming

### ISSUE THREAD

**Issue by A-NGJ** [A-NGJ/socialgraphs2022#15]
Some characters which have "/" in their name have been saved incorrectly.

For example, CT-43/002 is saved as 002. This is because of splitting an url over "/" and taking only the last element.

Please go through characters/ files and find those which have only numbers in name.
For each of those characters:
1. Change `name` so it's equal `display_name`
2. Rename the file, substituting `/` with `%2F` (url-encoded sign for "/")
3. Find corresponding entry in `character_pages.json` and fix the `Title` to be equal `name` and url. So instead of `https://starwars.fandom.com/wiki/002` url becomes `https://starwars.fandom.com/wiki/CT-43/002`

Once you are ready submit a PR :)

**Comment by ikka14** [comment]
completed :D
